import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8
padding.x = 15
padding.y = 15

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
action = "ResetFontSize"
