import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0  # Increased font size for high-DPI

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 15, y = 15 }
